# Generated by Django 5.0.4 on 2024-04-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('city_ascii', models.CharField(max_length=255, verbose_name='city_ascii')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('lng', models.FloatField(verbose_name='lng')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('iso2', models.CharField(max_length=10, verbose_name='iso2')),
                ('iso3', models.CharField(max_length=10, verbose_name='iso3')),
                ('admin_name', models.CharField(max_length=255, verbose_name='admin_name')),
                ('capital', models.CharField(max_length=255, verbose_name='capital')),
                ('population', models.FloatField(verbose_name='population')),
                ('cityid', models.IntegerField(verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
    ]
