# Generated by Django 5.0.4 on 2024-05-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_famouspeople_flowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='famouspeople',
            name='Occupation',
            field=models.CharField(default='Author', max_length=255, verbose_name='Occupation'),
            preserve_default=False,
        ),
    ]
