# Generated by Django 5.0.4 on 2024-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_famouspeople_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FruitsId', models.IntegerField(max_length=5, verbose_name='id')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(max_length=5, verbose_name='quantity')),
            ],
        ),
    ]
