# Generated by Django 5.0.4 on 2024-05-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_fruits'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entity', models.CharField(max_length=255, verbose_name='Entity')),
                ('Currency', models.CharField(max_length=255, verbose_name='Currency')),
                ('AlphabeticCode', models.CharField(max_length=255, verbose_name='AlphabeticCode')),
                ('NumericCode', models.IntegerField(null=True, verbose_name='NumericCode')),
                ('MinorUnit', models.IntegerField(verbose_name='MinorUnit')),
                ('WithdrawalDate', models.DateField(verbose_name='WithdrawalDate')),
            ],
        ),
        migrations.AlterField(
            model_name='fruits',
            name='FruitsId',
            field=models.IntegerField(verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
    ]
